export const TRANSLATE = 'TRANSLATE';
export const TRANSLATED = 'TRANSLATED';
export const DESTINY_LANGUAGE = 'DESTINY_LANGUAGE';
export const SOURCE_LANGUAGE = 'SOURCE_LANGUAGE';
export const HISTORIC_LIST = 'HISTORIC_LIST';
export const TRANSLATED_VALUES = 'TRANSLATED_VALUES';
